/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "castom_math_test.check" instead.
 */

#include "castom_math.h"

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

START_TEST(castom_test_abs) {
  for (int i = -1000; i <= 1000; i++) {
    ck_assert_int_eq(abs(i), castom_abs(i));
  }
}
END_TEST

START_TEST(castom_test_fabs) {
  ck_assert_double_eq_tol(fabs(15.5), castom_fabs(15.5), EPS_6);
  ck_assert_double_eq_tol(fabs(-15.3), castom_fabs(-15.3), EPS_6);
  ck_assert_double_eq_tol(fabs(0.0), castom_fabs(0.0), EPS_6);
  ck_assert_double_eq_tol(fabs(0.000004), castom_fabs(0.000004), EPS_6);
  ck_assert_double_eq_tol(fabs(-0.000004), castom_fabs(-0.000004), EPS_6);
  for (double i = -1000.0; i <= 1000.0; i += 0.01)
    ck_assert_double_eq_tol(fabs(i), castom_fabs(i), EPS_6);
}
END_TEST

START_TEST(scastom_test_pow) {
  for (double i = 0; i <= 5.0; i += 0.5) {
    for (double j = 1; j <= 9.4; j += 0.4) {
      ck_assert_double_eq_tol(pow(i, j), castom_pow(i, j), EPS_6);
    }
  }
  ck_assert_double_eq_tol(pow(1, 1), castom_pow(1, 1), EPS_6);
  ck_assert_double_eq_tol(pow(3, 0), castom_pow(3, 0), EPS_6);
  ck_assert_double_eq_tol(pow(3, 2), castom_pow(3, 2), EPS_6);
  ck_assert_double_eq_tol(pow(3.1, 4), castom_pow(3.1, 4), EPS_6);
  ck_assert_double_eq_tol(pow(3.1, 4.2), castom_pow(3.1, 4.2), EPS_6);
  ck_assert_double_eq_tol(pow(75, 16), castom_pow(75, 16), EPS_6);
  ck_assert_double_eq_tol(pow(35.1, 7.0), castom_pow(35.1, 7.0), EPS_6);
  ck_assert_double_eq_tol(pow(5.1, 4.51), castom_pow(5.1, 4.51), EPS_6);
  ck_assert_double_eq_tol(pow(5.1, 1.51), castom_pow(5.1, 1.51), EPS_6);
  ck_assert_double_eq_tol(pow(5.1, 0.511), castom_pow(5.1, 0.511), EPS_6);
  ck_assert_double_eq_tol(pow(0, 0.511), castom_pow(0, 0.511), EPS_6);
  ck_assert_double_eq_tol(pow(1.5, -100), castom_pow(1.5, -100), EPS_6);
  ck_assert_double_eq_tol(pow(-1.5, 8), castom_pow(-1.5, 8), EPS_6);
  ck_assert_double_eq_tol(pow(-100.0, 2), castom_pow(-100.0, 2), EPS_6);
  ck_assert_double_eq_tol(pow(0, 0), castom_pow(0, 0), EPS_6);
  ck_assert_double_eq_tol(pow(2.3, 300), castom_pow(2.3, 300), EPS_6);
}
END_TEST

START_TEST(castom_test_log) {
  for (double i = -1000.0; i < 0.0; i += 0.01) {
    ck_assert_ldouble_nan(log(i));
    ck_assert_ldouble_nan(castom_log(i));
  }

  for (double i = 0.1; i < 1000.0; i += 0.1)
    ck_assert_double_eq_tol(log(i), castom_log(i), EPS_6);

  ck_assert_double_eq_tol(log(1), castom_log(1), EPS_6);
  ck_assert_double_eq_tol(log(8), castom_log(8), EPS_6);
  ck_assert_double_eq_tol(log(0.1), castom_log(0.1), EPS_6);
  ck_assert_double_eq_tol(log(500), castom_log(500), EPS_6);
  ck_assert_double_eq_tol(log(1000000), castom_log(1000000), EPS_6);
  ck_assert_double_eq_tol(log(0.0000001), castom_log(0.0000001), EPS_6);
  ck_assert_double_eq_tol(log(1.5), castom_log(1.5), EPS_6);
  ck_assert_double_eq_tol(log(2), castom_log(2), EPS_6);
}
END_TEST

START_TEST(castom_test_exp) {
  for (double j = -20.0; j <= 80.0; j += 0.6) {
    ck_assert_double_eq_tol(exp(j), castom_exp(j), EPS_6);
  }
  ck_assert_double_eq_tol(exp(5), castom_exp(5), EPS_6);
  ck_assert_double_eq_tol(exp(19), castom_exp(19), EPS_6);
  ck_assert_double_eq_tol(exp(-5), castom_exp(-5), EPS_6);
  ck_assert_double_eq_tol(exp(-15), castom_exp(-15), EPS_6);
  ck_assert_double_eq_tol(exp(0.0000001), castom_exp(0.0000001), EPS_6);
  ck_assert_double_eq_tol(exp(0), castom_exp(0), EPS_6);
  ck_assert_double_eq_tol(exp(-20), castom_exp(-20), EPS_6);
  ck_assert_double_eq_tol(exp(50), castom_exp(50), EPS_6);
  ck_assert_double_eq_tol(exp(1), castom_exp(1), EPS_6);
}
END_TEST

START_TEST(castom_test_sqrt) {
  for (float j = 0.1; j <= 1200.8; j += 0.5) {
    ck_assert_double_eq_tol(sqrt(j), castom_sqrt(j), EPS_6);
  }
  ck_assert_double_eq_tol(sqrt(1), castom_sqrt(1), EPS_6);
  ck_assert_double_eq_tol(sqrt(8), castom_sqrt(8), EPS_6);
  ck_assert_double_eq_tol(sqrt(0.1), castom_sqrt(0.1), EPS_6);
  ck_assert_double_eq_tol(sqrt(500), castom_sqrt(500), EPS_6);
  ck_assert_double_eq_tol(sqrt(1000000), castom_sqrt(1000000), EPS_6);
  ck_assert_double_eq_tol(sqrt(0.0000001), castom_sqrt(0.0000001), EPS_6);
  ck_assert_double_eq_tol(sqrt(1.5), castom_sqrt(1.5), EPS_6);
  ck_assert_double_eq_tol(sqrt(2), castom_sqrt(2), EPS_6);
  ck_assert_ldouble_nan(castom_sqrt(-2));
}
END_TEST

START_TEST(castom_test_ceil) {
  ck_assert_double_eq(ceil(1.000001), castom_ceil(1.000001));
  ck_assert_double_eq(ceil(8.44), castom_ceil(8.44));
  ck_assert_double_eq(ceil(0.1), castom_ceil(0.1));
  ck_assert_double_eq(ceil(500.55), castom_ceil(500.55));
  ck_assert_double_eq(ceil(1000000.0), castom_ceil(1000000.0));
  ck_assert_double_eq(ceil(0.0000001), castom_ceil(0.0000001));

  ck_assert_double_eq(ceil(1.5), castom_ceil(1.5));
  ck_assert_double_eq(ceil(0.0), castom_ceil(0.0));
}
END_TEST

START_TEST(castom_test_floor) {
  ck_assert_double_eq(floor(1.000001), castom_floor(1.000001));
  ck_assert_double_eq(floor(8.44), castom_floor(8.44));
  ck_assert_double_eq(floor(0.1), castom_floor(0.1));
  ck_assert_double_eq(floor(500.55), castom_floor(500.55));
  ck_assert_double_eq(floor(1000000.0), castom_floor(1000000.0));
  ck_assert_double_eq(floor(0.0000001), castom_floor(0.0000001));
  ck_assert_double_eq(floor(1.5), castom_floor(1.5));
  ck_assert_double_eq(floor(0.0), castom_floor(0.0));
  ck_assert_double_eq(floor(-1.000001), castom_floor(-1.000001));
  ck_assert_double_eq(floor(-8.44), castom_floor(-8.44));
  ck_assert_double_eq(floor(-0.1), castom_floor(-0.1));
  ck_assert_double_eq(floor(-500.55), castom_floor(-500.55));
  ck_assert_double_eq(floor(-1000000.0), castom_floor(-1000000.0));
  ck_assert_double_eq(floor(-0.0000001), castom_floor(-0.0000001));
  ck_assert_double_eq(floor(-1.5), castom_floor(-1.5));
  ck_assert_double_eq(floor(-0.0), castom_floor(-0.0));
}
END_TEST

START_TEST(castom_test_trunc) {
  ck_assert_double_eq(trunc(1.000001), castom_trunc(1.000001));
  ck_assert_double_eq(trunc(8.44), castom_trunc(8.44));
  ck_assert_double_eq(trunc(0.1), castom_trunc(0.1));
  ck_assert_double_eq(trunc(500.55), castom_trunc(500.55));
  ck_assert_double_eq(trunc(1000000.0), castom_trunc(1000000.0));
  ck_assert_double_eq(trunc(0.0000001), castom_trunc(0.0000001));
  ck_assert_double_eq(trunc(1.5), castom_trunc(1.5));
  ck_assert_double_eq(trunc(0.0), castom_trunc(0.0));
  ck_assert_double_eq(trunc(-1.000001), castom_trunc(-1.000001));
  ck_assert_double_eq(trunc(-8.44), castom_trunc(-8.44));
  ck_assert_double_eq(trunc(-0.1), castom_trunc(-0.1));
  ck_assert_double_eq(trunc(-500.55), castom_trunc(-500.55));
  ck_assert_double_eq(trunc(-1000000.0), castom_trunc(-1000000.0));
  ck_assert_double_eq(trunc(-0.0000001), castom_trunc(-0.0000001));
  ck_assert_double_eq(trunc(-1.5), castom_trunc(-1.5));
  ck_assert_double_eq(trunc(-0.0), castom_trunc(-0.0));
}
END_TEST

START_TEST(castom_test_fmod) {
  ck_assert_double_eq_tol(fmod(10.5, -3.0), castom_fmod(10.5, -3.0), EPS_6);
  ck_assert_double_eq_tol(fmod(-8.1, 4.0), castom_fmod(-8.1, 4.0), EPS_6);
  ck_assert_double_eq_tol(fmod(-0.0, 4.4), castom_fmod(-0.0, 4.4), EPS_6);
  ck_assert_double_eq_tol(fmod(0.0, 1.4), castom_fmod(0.0, 1.4), EPS_6);
  ck_assert_double_eq_tol(fmod(10.1, 0.051), castom_fmod(10.1, 0.051), EPS_6);
  ck_assert_double_eq_tol(fmod(100000.1, -0.1), castom_fmod(100000.1, -0.1),
                          EPS_6);
  ck_assert_double_eq_tol(fmod(100.1, 0.1), castom_fmod(100.1, 0.1), EPS_6);
  ck_assert_double_eq_tol(fmod(0.00005001, 0.0000001),
                          castom_fmod(0.00005001, 0.0000001), EPS_6);
  ck_assert_double_eq_tol(fmod(1.5, 100.0), castom_fmod(1.5, 100.0), EPS_6);
  ck_assert_double_eq_tol(fmod(0.0, 1.0), castom_fmod(0.0, 1.0), EPS_6);
}
END_TEST

START_TEST(castom_test_asin) {
  for (float j = -0.99; j <= 0.99; j += 0.01) {
    ck_assert_double_eq_tol(asin(j), castom_asin(j), EPS_6);
  }
  ck_assert_double_eq_tol(asin(S21_M_PI / 4), castom_asin(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(asin(S21_M_PI / 4), castom_asin(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(asin(-0.99), castom_asin(-0.99), EPS_6);
  ck_assert_double_eq_tol(asin(0.3), castom_asin(0.3), EPS_6);
  ck_assert_double_eq_tol(asin(0.45), castom_asin(0.45), EPS_6);
  ck_assert_double_eq_tol(asin(0.0), castom_asin(0.0), EPS_6);
  ck_assert_double_eq_tol(asin(-0.18), castom_asin(-0.18), EPS_6);
  ck_assert_double_eq_tol(asin(0.360), castom_asin(0.360), EPS_6);
  ck_assert_double_eq_tol(asin(0.255), castom_asin(0.255), EPS_6);
  ck_assert_double_eq_tol(asin(-0.50), castom_asin(-0.50), EPS_6);
  ck_assert_double_eq_tol(asin(0.000001), castom_asin(0.000001), EPS_6);
  ck_assert_double_eq_tol(asin(1.0), castom_asin(1.0), EPS_6);
  ck_assert_double_eq_tol(asin(-1.0), castom_asin(-1.0), EPS_6);
  // ck_assert_ldouble_nan(asin(5));
  // ck_assert_ldouble_nan(castom_asin(5));
}
END_TEST

START_TEST(castom_test_cos) {
  for (float j = -721; j < 721; j += 0.1) {
    ck_assert_double_eq_tol(cos(j), castom_cos(j), EPS_6);
  }
  ck_assert_double_eq_tol(cos(30.0), castom_cos(30.0), EPS_6);
  ck_assert_double_eq_tol(cos(45.0), castom_cos(45.0), EPS_6);
  ck_assert_double_eq_tol(cos(0.0), castom_cos(0.0), EPS_6);
  ck_assert_double_eq_tol(cos(180.0), castom_cos(180.0), EPS_6);
  ck_assert_double_eq_tol(cos(360.0), castom_cos(360.0), EPS_6);
  ck_assert_double_eq_tol(cos(25.5), castom_cos(25.5), EPS_6);
  ck_assert_double_eq_tol(cos(-5.0), castom_cos(-5.0), EPS_6);
  ck_assert_double_eq_tol(cos(500.21), castom_cos(500.21), EPS_6);
  ck_assert_double_eq_tol(cos(0.000001), castom_cos(0.000001), EPS_6);
  ck_assert_double_eq_tol(cos(0.0001), castom_cos(0.0001), EPS_6);
}
END_TEST

START_TEST(castom_test_acos) {
  for (float j = -0.99; j <= 0.99; j += 0.01) {
    ck_assert_double_eq_tol(acos(j), castom_acos(j), EPS_6);
  }
  ck_assert_double_eq_tol(acos(S21_M_PI / 4), castom_acos(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(acos(S21_M_PI / 4), castom_acos(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(acos(-0.99), castom_acos(-0.99), EPS_6);
  ck_assert_double_eq_tol(acos(0.3), castom_acos(0.3), EPS_6);
  ck_assert_double_eq_tol(acos(0.45), castom_acos(0.45), EPS_6);
  ck_assert_double_eq_tol(acos(0.0), castom_acos(0.0), EPS_6);
  ck_assert_double_eq_tol(acos(-0.18), castom_acos(-0.18), EPS_6);
  ck_assert_double_eq_tol(acos(0.360), castom_acos(0.360), EPS_6);
  ck_assert_double_eq_tol(acos(0.255), castom_acos(0.255), EPS_6);
  ck_assert_double_eq_tol(acos(-0.50), castom_acos(-0.50), EPS_6);
  ck_assert_double_eq_tol(acos(0.000001), castom_acos(0.000001), EPS_6);
  // ck_assert_ldouble_nan(acos(1.000000000001));
  // ck_assert_ldouble_nan(castom_acos(1.000000000001));
}
END_TEST

START_TEST(castom_test_atan) {
  for (double j = -100.0; j < 100.0; j += 0.1) {
    ck_assert_double_eq_tol(atan(j), castom_atan(j), EPS_6);
  }

  ck_assert_double_eq_tol(atan(S21_M_PI / 4), castom_atan(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(atan(-S21_M_PI / 4), castom_atan(-S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(atan(-0.99), castom_atan(-0.99), EPS_6);
  ck_assert_double_eq_tol(atan(0.3), castom_atan(0.3), EPS_6);
  ck_assert_double_eq_tol(atan(0.45), castom_atan(0.45), EPS_6);
  ck_assert_double_eq_tol(atan(0.0), castom_atan(0.0), EPS_6);
  ck_assert_double_eq_tol(atan(-0.18), castom_atan(-0.18), EPS_6);
  ck_assert_double_eq_tol(atan(0.360), castom_atan(0.360), EPS_6);
  ck_assert_double_eq_tol(atan(0.255), castom_atan(0.255), EPS_6);
  ck_assert_double_eq_tol(atan(-0.50), castom_atan(-0.50), EPS_6);
  ck_assert_double_eq_tol(atan(0.000001), castom_atan(0.000001), EPS_6);
  ck_assert_double_eq_tol(atan(2.1), castom_atan(2.1), EPS_6);
  ck_assert_double_eq_tol(atan(1), castom_atan(1), EPS_6);
  ck_assert_double_eq_tol(atan(-1), castom_atan(-1), EPS_6);
  ck_assert_double_eq_tol(atan(-50), castom_atan(-50), EPS_6);
  ck_assert_double_eq_tol(atan(0), castom_atan(0), EPS_6);
}
END_TEST

START_TEST(castom_test_sin) {
  for (double j = -10.0; j <= 10.0; j += 0.01) {
    ck_assert_double_eq_tol(sin(j), castom_sin(j), EPS_6);
  }
  ck_assert_double_eq_tol(sin(0), castom_sin(0), EPS_6);
  ck_assert_double_eq_tol(sin(S21_M_PI / 6), castom_sin(S21_M_PI / 6), EPS_6);
  ck_assert_double_eq_tol(sin(S21_M_PI / 4), castom_sin(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(sin(S21_M_PI / 3), castom_sin(S21_M_PI / 3), EPS_6);
  ck_assert_double_eq_tol(sin(S21_M_PI / 2), castom_sin(S21_M_PI / 2), EPS_6);
  ck_assert_double_eq_tol(sin(S21_M_PI), castom_sin(S21_M_PI), EPS_6);
  ck_assert_double_eq_tol(sin(3.0 * S21_M_PI / 2.0),
                          castom_sin(3.0 * S21_M_PI / 2.0), EPS_6);
  ck_assert_double_eq_tol(sin(2.0 * S21_M_PI), castom_sin(2.0 * S21_M_PI), EPS_6);
}
END_TEST

START_TEST(castom_test_tan) {
  for (double j = -10.0; j <= 10.0; j += 0.1) {
    ck_assert_double_eq_tol(tan(j), castom_tan(j), EPS_6);
  }
  ck_assert_double_eq_tol(tan(360.0), castom_tan(360.0), EPS_6);
  ck_assert_double_eq_tol(tan(0.000001), castom_tan(0.000001), EPS_6);
  ck_assert_double_eq_tol(tan(30.0), castom_tan(30.0), EPS_6);
  ck_assert_double_eq_tol(tan(45.0), castom_tan(45.0), EPS_6);
  ck_assert_double_eq_tol(tan(0.0), castom_tan(0.0), EPS_6);
  ck_assert_double_eq_tol(tan(180.0), castom_tan(180.0), EPS_6);
  ck_assert_double_eq_tol(tan(25.5), castom_tan(25.5), EPS_6);
  ck_assert_double_eq_tol(tan(-5.0), castom_tan(-5.0), EPS_6);
  ck_assert_double_eq_tol(tan(500.21), castom_tan(500.21), EPS_6);
  ck_assert_double_eq_tol(tan(0.0001), castom_tan(0.0001), EPS_6);
  ck_assert_double_eq_tol(tan(S21_M_PI / 6), castom_tan(S21_M_PI / 6), EPS_6);
  ck_assert_double_eq_tol(tan(S21_M_PI / 4), castom_tan(S21_M_PI / 4), EPS_6);
  ck_assert_double_eq_tol(tan(S21_M_PI / 3), castom_tan(S21_M_PI / 3), EPS_6);
  ck_assert_double_eq_tol(tan(S21_M_PI), castom_tan(S21_M_PI), EPS_6);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, castom_test_abs);
  tcase_add_test(tc1_1, castom_test_fabs);
  tcase_add_test(tc1_1, scastom_test_pow);
  tcase_add_test(tc1_1, castom_test_log);
  tcase_add_test(tc1_1, castom_test_exp);
  tcase_add_test(tc1_1, castom_test_sqrt);
  tcase_add_test(tc1_1, castom_test_ceil);
  tcase_add_test(tc1_1, castom_test_floor);
  tcase_add_test(tc1_1, castom_test_trunc);
  tcase_add_test(tc1_1, castom_test_fmod);
  tcase_add_test(tc1_1, castom_test_asin);
  tcase_add_test(tc1_1, castom_test_cos);
  tcase_add_test(tc1_1, castom_test_acos);
  tcase_add_test(tc1_1, castom_test_atan);
  tcase_add_test(tc1_1, castom_test_sin);
  tcase_add_test(tc1_1, castom_test_tan);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
